### ISSUE TITLE
ni8mare - `FootiumGeneralPaymentContract` and `FootiumAcademy` cannot update the `footiumClub` address. This may cause functions to revert for new club owners.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-footium-judging#107]
ni8mare

high

# `FootiumGeneralPaymentContract` and `FootiumAcademy` cannot update the `footiumClub` address. This may cause functions to revert for new club owners.

## Summary
`FootiumGeneralPaymentContract` and `FootiumAcademy` do not have setter functions to update the `footiumClub` address. So, club owners minted by `FootiumClubMinter` using a new address for `footiumClub` will not be able to call functions like `makePayment` and `mintPlayer`.

## Vulnerability Detail

The contract `FootiumClubMinter` mints a new club to a receiver and 20 new players for the club. `FootiumClubMinter` also has a setter function that updates the `footiumClub` address:

```solidity
    /**
     * @dev Updates Footium Clubs contract address.
     * @param _footiumClub Footium Clubs contract address.
     * @dev Only owner address allowed.
     */
    function setClubAddress(IFootiumClub _footiumClub) external onlyOwner {
        footiumClub = _footiumClub;
    }
```
But, this setter function is absent from `FootiumGeneralPaymentContract` and `FootiumAcademy`. This could lead to critical problems for new club owners.

Let's say that the owner updates for whatever reason the `footiumClub` address in the `FootiumClubMinter`. The owner calls the `mint` function to mint a club and players for a receiver. Note that this new club was minted for the receiver using an updated address for the `footiumClub`. The `FootiumGeneralPaymentContract` is not aware of this updated `footiumClub` address and has no way to update it because of a lack of setter functions. For `FootiumGeneralPaymentContract`, the `footiumClub` is still the older address that was first initialised. When new users(club owners that were minted using the updated address in `FootiumGeneralPaymentContract`) use the function `makePayment`, the following condition will revert:

```solidity
        // Require that the sender is the owner of the club
        if (msg.sender != footiumClub.ownerOf(_clubId)) {
            revert NotClubOwner(_clubId, msg.sender);
        }
```

This is because the above conditional checks for the owner of the `_clubId` using an older address for `footiumClub`. The `_clubId` was minted using the updated address. Hence the condition fails and the new club owner is never able to make a payment.

Similarly, in the `FootiumAcademy` which also lacks these setter functions, the new club owner(minted using the updated address) is never able to call `mintPlayer` because the same condition reverts. `FootiumAcademy` too would be using the older address for the `footiumClub`. 

This also leads to another vulnerability in `FootiumAcademy`. A `clubId` could already exist for the older address of the `footiumClub`. So, an older club owner with the same `clubId` associated with the older`footiumClub` address, could simply call `mintPlayer` and mint themselves a player with the `playerId` that is supposed to be meant for a new club owner.

## Impact
Functions like `makePayment` and `mintPlayer` will revert.

## Code Snippet

[makePayment](https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumGeneralPaymentContract.sol#L84):

```solidity
    /**
     * @notice Makes a payment for the given feature.
     * @param _clubId Club ID.
     * @param _message A message describing a feature to pay for.
     * @dev This function is payable.
     * Emits a {PaymentMade} event.
     */
    function makePayment(uint256 _clubId, string calldata _message)
        external
        payable
        whenNotPaused
        nonReentrant
    {
```

[mintPlayer](https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumAcademy.sol#L96): 

```solidity
    /**
     * @notice Mint a player.
     * @param clubId The ID of the club to receive the players.
     * @param playerId The ID of the player to be minted.
     * @param mintProof The proof that a certain player can be minted.
     * @dev Only the owner can mint players to their club.
     */
    function mintPlayer(
        uint256 clubId,
        string calldata playerId,
        bytes32[] calldata mintProof
    ) external payable whenNotPaused nonReentrant {
```

## Tool used

Manual Review

## Recommendation
Add the appropriate setter functions in `FootiumGeneralPaymentContract` and `FootiumAcademy`

**Comment by NishithPat** [comment]
Escalate

Firstly, I want to point out that my recommendation to add a setter function to update the `FootiumClub` address in `FootiumGeneralPaymentContract` and `FootiumAcademy` is incorrect, as it can introduce more bugs. But, the impact of the issue is still valid and needs to be looked at.

In our discussions with the judge, they had suggested that if a new `FootiumClub` contract is redeployed then a corresponding set of `footiumClubGeneralPayment` and `FootiumAcademy` contracts will be deployed again where the `footiumClub` address within these deployed contracts would now point to this new `FootiumClub` address. They also said that while migrating to these new contracts, the old club owners would mint new NFTs corresponding to these new sets of contracts so that they could keep using the `mintPlayers` function in the new `FootiumAcademy` contract while pausing the same minting function in the older `FootiumAcademy` contracts.

But, this would be very difficult to achieve. If it were to come to a migration of all contracts, the owner simply pausing the minting on the old contracts would not suffice. Because it still does not stop the transfers (selling on secondary markets) of the NFTs, as mentioned here - https://github.com/sherlock-audit/2023-12-footium-judging/issues/8. So taking a snapshot of the current owner state would be very hard. If the owner were to mint new NFTs for the older club owners using this snapshot, bad actors could simply sell their clubs before this minting. These bad actors will again be owning the same club while profiting off the sale of their older club NFT. Hence, the migration in this manner would not be very feasible.

Also, If it was the case that these contracts would be deployed again with a new `FootiumClub` contract, then there would never be a need for the `FootiumClubMinter` to have the setter functions to update the `footiumClub` address. The fact that it has them, suggests the protocol intends to use them to update the address.

The important point I am trying to raise here is that updating the `footiumClub` address through these setter functions would always lead to a vulnerability.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Firstly, I want to point out that my recommendation to add a setter function to update the `FootiumClub` address in `FootiumGeneralPaymentContract` and `FootiumAcademy` is incorrect, as it can introduce more bugs. But, the impact of the issue is still valid and needs to be looked at.
> 
> In our discussions with the judge, they had suggested that if a new `FootiumClub` contract is redeployed then a corresponding set of `footiumClubGeneralPayment` and `FootiumAcademy` contracts will be deployed again where the `footiumClub` address within these deployed contracts would now point to this new `FootiumClub` address. They also said that while migrating to these new contracts, the old club owners would mint new NFTs corresponding to these new sets of contracts so that they could keep using the `mintPlayers` function in the new `FootiumAcademy` contract while pausing the same minting function in the older `FootiumAcademy` contracts.
> 
> But, this would be very difficult to achieve. If it were to come to a migration of all contracts, the owner simply pausing the minting on the old contracts would not suffice. Because it still does not stop the transfers (selling on secondary markets) of the NFTs, as mentioned here - https://github.com/sherlock-audit/2023-12-footium-judging/issues/8. So taking a snapshot of the current owner state would be very hard. If the owner were to mint new NFTs for the older club owners using this snapshot, bad actors could simply sell their clubs before this minting. These bad actors will again be owning the same club while profiting off the sale of their older club NFT. Hence, the migration in this manner would not be very feasible.
> 
> Also, If it was the case that these contracts would be deployed again with a new `FootiumClub` contract, then there would never be a need for the `FootiumClubMinter` to have the setter functions to update the `footiumClub` address. The fact that it has them, suggests the protocol intends to use them to update the address.
> 
> The important point I am trying to raise here is that updating the `footiumClub` address through these setter functions would always lead to a vulnerability.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@Czar102 Refer to the private threads on discord for discussions between me, sponsor and the watson titled "Questions regarding issue 107". I believe that is sufficient to come to a conclusion.

**Comment by 0xEVom** [comment]
> Also, If it was the case that these contracts would be deployed again with a new `FootiumClub` contract, then there would never be a need for the `FootiumClubMinter` to have the setter functions to update the `footiumClub` address. The fact that it has them, suggests the protocol intends to use them to update the address.

This is an assumption by the Watson. The presence of this function isn't a vulnerability in itself, and it could have been mistakenly left over from previous functionality. No public documentation suggested the sponsor required it to function as an upgrade mechanism.

Besides, even if the club contract address was to be updated through this function, that wouldn't necessarily require a full migration. The contract could simply start minting v2 clubs while v1 clubs maintain their functionality and value.

**Comment by matejdrazic** [comment]
> This is an assumption by the Watson. The presence of this function isn't a vulnerability in itself, and it could have been mistakenly left over from previous functionality. No public documentation suggested the sponsor required it to function as an upgrade mechanism.

But it's a correct assumption. All we have to go by is the code provided.

> Besides, even if the club contract address was to be updated through this function, that wouldn't necessarily require a full migration. The contract could simply start minting v2 clubs while v1 clubs maintain their functionality and value.

Yes, on first look it seems like that but I think some functions break when you have clubs and players with the same ID. See FootiumGeneralPaymentContract::makePayment()

**Comment by Czar102** [comment]
I agree with the Lead Judge and the sponsor.

The proposed use case by them is valid. And the argument against its validity from the escalator is:
> But, this would be very difficult to achieve.

Which is not a vulnerability.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [NishithPat](https://github.com/sherlock-audit/2023-12-footium-judging/issues/107/#issuecomment-1868598032): rejected
